[fbcnms-alarms] Update alert detail pane style
facebookincubator/fbc-js-core pull request #105
Opened 2021-06-14 12:16 UTC by HannaFar

Updated alert detail pane style
Added Chip view option to severity indicator component 

<img width="440" alt="Capture d’écran 2021-06-14 à 14 14 11" src="https://user-images.githubusercontent.com/26038920/121890766-fea4f780-cd1a-11eb-9d00-e2bf18416ec2.png">

Test Plan:
yarn run test

2021-06-15 22:05 UTC, andreilee requested changes
Looks good, just some nits. Mind the `eslint` as well

2021-06-15 22:05 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/AlarmsApi.js
> +  troubleshootingTitle?: string,
These shouldn't be nullable. Either a link + title are provided, but not one or the other.

2021-06-15 22:05 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/AlarmsApi.js
> +  }) => Promise<TroubleshootingLinkType>,
```suggestion
  }) => Promise<?TroubleshootingLinkType>,
```

2021-06-15 22:05 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/AlarmsApi.js
> +  }) => Promise<TroubleshootingLinkType>,
Some alerts may not have troubleshooting documentation, so this should return a nullable value.

2021-06-15 22:05 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
> +          <Grid item>
1. What should we be showing if there's no link available? Should check with the designer here
2. The divider probably shouldn't show if there's no link.

2021-06-15 22:05 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/severity/SeverityIndicator.js
> +  chip?: boolean,
Can you add comments explaining what `chip` is?

2021-06-15 22:05 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/severity/SeverityIndicator.js
>    severity: string,
What are the allowable values for `severity`? Or is it literally just any string any we don't have enforcement?

2021-06-16 13:40 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
> +          <Grid item>
I understood that if we don't have the link we don't show anything

2021-06-16 13:55 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/severity/SeverityIndicator.js
>    severity: string,
It's any string

2021-06-16 18:14 UTC, aclave1 commented
can you post a before/after screenshot?

2021-06-16 18:34 UTC, aclave1 requested changes

2021-06-16 18:34 UTC, aclave1 commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
> +  const {error, response: link} = apiUtil.useAlarmsApi(
you can't await inside of a react-component's render function. this is a react hook so it awaits internally.

2021-06-16 18:34 UTC, aclave1 commented on fbcnms-packages/fbcnms-alarms/components/AlarmsApi.js
> +  troubleshootingLink: string,
i'd shorten these to just link and title since Troubleshooting is already in the type name

2021-06-16 18:34 UTC, aclave1 commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
> +      {Object.keys(link ?? {}).length > 0 && (
getTroubleshootingLink in AlarmsAPI returns a nullable TroubleshootingLink and we check for null here to hide a missing troubleshooting link, yet the implementation in fbcnms-packages/fbcnms-ui/insights/Alarms/AlarmApi.js returns an object(not null) - every alert will show "View Documentation" with an empty link

2021-06-16 18:34 UTC, aclave1 commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
> +      {Object.keys(link ?? {}).length > 0 && (
let's extract this to a component like `<AlertTroubleshootingLink alertname={alertname}/>` and call useAlarmsAPI and apiUtil.getTroubleshootingLink inside there. My goal for this suggestion is separation of concerns for querying/displaying the troubleshooting link.

2021-06-16 18:34 UTC, aclave1 commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/MetricAlertViewer.js
> -        <ObjectViewer object={extraAnnotations} />
i think extra annotations are still important for the user to see, just maybe they should be hidden behind a collapse panel or something. Was removing annotations part of the designs? I haven't looked at them in a while

2021-06-16 19:00 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
> +      {Object.keys(link ?? {}).length > 0 && (
Yes I don't have the links yet and I'm not sure how it will look like

2021-06-18 19:18 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/AlertDetailsPane.js
> +      {Object.keys(link ?? {}).length > 0 && (
I changed it to display the link only if we have a link

2021-06-18 19:20 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/AlertDetails/MetricAlertViewer.js
> -        <ObjectViewer object={extraAnnotations} />
I moved it to a collapse panel that the user can expand by clicking on Show More Details (It's in the description screenshot)

2021-06-22 06:26 UTC, andreilee commented
Looks good!

2021-06-22 06:27 UTC, andreilee approved these changes

2021-06-22 06:27 UTC, merged