[fbcnms-alarms]: Use material-table
facebookincubator/fbc-js-core pull request #113
Opened 2021-07-14 17:57 UTC by HannaFar

2021-07-15 21:51 UTC, andreilee reviewed
Please make sure to add before/after screenshots before publishing.

Considering the frequent re-use of `SimpleTable`, I think there needs to be some more extensive comments/documentation on usage, as well as descriptions of various arguments/options.

2021-07-15 21:51 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/AlertRules.js
> +        field: 'name',
Capitalize the column titles

2021-07-15 21:51 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/Suppressions.js
> +          {title: 'created by', field: 'createdBy'},
Capitalize the column titles here as well

2021-07-15 21:51 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/alertmanager/Suppressions.js
> +        data-testid="suppresions"
typo here

2021-07-15 21:51 UTC, andreilee commented on fbcnms-packages/fbcnms-alarms/components/table/SimpleTable.js
> +};
Add comments to describe how to use these options

2021-07-16 15:28 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/table/SimpleTable.js
> -  hideFields,
This wasn't used so I removed it

2021-07-16 15:28 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/table/SimpleTable.js
> -function ChipCell({value, classes}: CellProps<string>) {
This wasn't used

2021-07-16 16:37 UTC, HannaFar commented on fbcnms-packages/fbcnms-alarms/components/table/SimpleTable.js
> +};
I removed rowstyle and headerstyle, we are not using it

2021-09-08 22:35 UTC, andreilee requested changes
Could you rebase and bump the version number of `@fbcnms/alarms` to 0.4.0?

2021-09-10 00:32 UTC, andreilee approved these changes

2021-09-10 00:32 UTC, merged