chore: upgrade passport-saml
facebookincubator/fbc-js-core pull request #136
Opened 2021-11-22 02:33 UTC by lucasgonze

chore: Upgrade passport-saml from 1.0.0 to 3.1.0 to pick up security-related improvements upstream.

Fixes https://github.com/facebookincubator/fbc-js-core/issues/135

This is the same as https://github.com/facebookincubator/fbc-js-core/pull/120#partial-pull-merging but with a new package number to enable npm to publish the change.

Signed-off-by: Lucas Gonze <lucas@gonze.com>

2021-11-22 02:36 UTC, lucasgonze commented
There are two obstacles to this PR.

1. The checks that were not successful at https://github.com/facebookincubator/fbc-js-core/pull/120#partial-pull-merging will probably fail again. The fix is to upgrade the version of node used in the CI from 10.24.1 to at least 12. However, it is possible that the need for node 12 is a breaking change in this package. Discuss.

2. I haven't yet gotten the tests to run on my machine. However, this may not matter if pushing the PR causes the tests to run in the CI.

2021-11-22 02:45 UTC, lucasgonze commented
I am changing the status to "ready for review" in order to run tests in the CI. This will verify that the version of node there is still v10. If it has been upgraded then tests will pass and we really are ready for review, and if it hasn't then tests will fail. Nothing to lose.

2021-12-14 19:28 UTC, andreilee requested changes
Bump package version numbers, which will trigger release after merge.

Also yarn.lock should be updated

2021-12-14 19:28 UTC, andreilee commented on fbcnms-packages/fbcnms-auth/package.json
>      "passport-local": "^1.0.0",
version of `@fbcnms/auth` needs to be bumped - probably to `0.1.4`

2021-12-14 23:16 UTC, lucasgonze commented on fbcnms-packages/fbcnms-auth/package.json
>      "passport-local": "^1.0.0",
Bumped versions and added yarn.lock.

2021-12-27 21:13 UTC, lucasgonze commented
Consolidating this PR with https://github.com/facebookincubator/fbc-js-core/pull/148. These two are closely related, so we might as well reduce the work and simplify the review process.

2021-12-27 21:13 UTC, closed without merging