chore: update openid-client to 5.1.0
facebookincubator/fbc-js-core pull request #138
Opened 2021-12-09 01:44 UTC by lucasgonze

Fixes https://github.com/facebookincubator/fbc-js-core/issues/137

I tested by running unit tests. They passed. However caution is warranted because I am upgrading a package used here by 3 major versions.

Signed-off-by: Lucas Gonze <lucas@gonze.com>

2021-12-09 22:38 UTC, andreilee requested changes

2021-12-09 22:38 UTC, andreilee commented on fbcnms-packages/fbcnms-auth/package.json
>    "dependencies": {
For upgraded dependencies, you'll want to bump the version numbers, and also run yarn to update `yarn.lock` file.

2021-12-10 21:16 UTC, lucasgonze commented
Bumped version numbers and added yarn.lock. Ready for merge.

2021-12-14 19:27 UTC, andreilee approved these changes

2021-12-14 19:27 UTC, merged